persistence:
  enabled: false

logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false
    config.reload.automatic: true

logstashPipeline:
  uptime.conf: |
    output {
      stdout {
        codec => rubydebug   
      }
      elasticsearch {
        hosts => ["http://10.0.0.4:9200"]
        user => '${ELASTICSEARCH_USERNAME}'
        password => '${ELASTICSEARCH_PASSWORD}'
        index => "logstash-%{+YYYY.MM.dd.HH}"
      }
    }
# cacert => '/usr/share/logstash/config/certs/ca.crt'
extraEnvs:
  - name: "ELASTICSEARCH_USERNAME"
    valueFrom:
      secretKeyRef:
        name: es-username
        key: username
  - name: "ELASTICSEARCH_PASSWORD"
    valueFrom:
      secretKeyRef:
        name: es-password
        key: password

# secretMounts: 
#   - name: ca-config
#     secretName: ca-config
#     path: /usr/share/logstash/config/certs

  # - name: elasticsearch-master-certs
  #   secretName: elasticsearch-master-certs
  #   path: /usr/share/logstash/config/certs
service:
  name: logstash
  type: ClusterIP
  ports:
    - name: beats
      port: 5044
      targetPort: 5044
  selector:
    app: logstash-logstash

