api: <api_path>
username: elastic
password: <elastic_password>
prometheusApi: <prometheus_api_path>
namespace: test-hotel-reservation
trace_index: .ds-traces-apm-default-*
logstash_index: logstash-*
kubernetes_path: '~/.kube/config'
es_use_cert: 'False'
es_cert_path: <path_to_es_cert>

