# api: https://10.10.1.202:9200
api: http://localhost:9200
username: elastic
password: 1bk5VMvqtLvRnMcc3yl0
prometheusApi: http://localhost:32000
namespace: test-hotel-reservation
trace_index: .ds-traces-apm-default-*
logstash_index: logstash-*
kubernetes_path: '~/.kube/config'
es_use_cert: 'False'
es_cert_path: '/home/yinfangchen/AIOpsLab/aiopslab/observor/ca.pem'
